version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1.8-browsers
    steps:
      - checkout
      # - run: sudo apt install -y libsqlite3-dev
      # - run: composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./*

  deploy:
    docker:
      - image: amazonlinux
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Setup AWS-CLI
          command: |
            curl -kL https://bootstrap.pypa.io/get-pip.py | python
            pip install awscli --upgrade
            aws --version
            ls
      - deploy:
          name: Deploy to EC2
          command: |
              GITHUB_REPO=`echo $CIRCLE_REPOSITORY_URL | sed -e 's/git@github.com://' | sed -e 's/.git$//' `
              DEPLOYMENTID=`aws deploy create-deployment \
                  --application-name StartByCircleCI \
                  --github-location repository=${GITHUB_REPO},commitId=${CIRCLE_SHA1} \
                  --deployment-group-name ${CIRCLE_BRANCH}-group \
                  --region ap-northeast-1 \
                  --query 'deploymentId' --output text`
              aws deploy wait deployment-successful --region ap-northeast-1 --deployment-id $DEPLOYMENTID

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - staging
      - deploy:
          requires:
            - build
